version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-lojacorr
    container_name: laravel-lojacorr
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - 9000:9000
  web:
    image: nginx:latest
    container_name: laravel-web-lojacorr
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  db:
    image: mysql:5.7
    container_name: laravel-db-lojacorr
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel-lojacorr
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - "3307:3306"
